version: '3.8'

services:
  app:
    image: nagamochi:latest
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - DB_URL
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

  test:
    image: postgres:latest
    ports:
      - "55432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=nagamochi
